version: '3'

services:

  employeemanagementVue:
    container_name: employeemanagementVue
    image: employeemanagement/vue:latest
    restart: always
    ports:
      - 8080:80
    volumes:
      - employeemanagementVue:/data
    networks:
      - frontend
      
networks:
    frontend:
      driver: bridge

volumes:
  employeemanagementVue:
